#!/usr/bin/bash
set -e
# Clean up
rm -rf env frontend/node_modules
rm -rf flaskr/static flaskr/templates

cd frontend
npm ci
npm run build

# Launch flask server
cd ..
python3 -m venv env
source env/bin/activate
pip install -r flaskr/requirements.txt
flask --app flaskr --debug run
